/*
 * @Author: huangzhenxiang
 * @Date: 2022-04-22 11:25:28
 * @LastEditors: huangzhenxiang
 * @LastEditTime: 2022-04-29 14:26:00
 */
// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElMessage: typeof import('element-plus/es')['ElMessage']
}
export {}
